### ISSUE TITLE
Doesn't poll state of devices?

### ISSUE THREAD

**Issue by drebes** [jbree/homebridge-cec-accessory#1]
I tried your plugin and it works really well, thank you.

However, I noticed that when I turn on one of my playback devices (Apple TV or PS3) that also triggers the TV to switch on (which is fine), however the state of the TV is not updated on homebridge/HomeKit.

I'm not sure how often HomeKit polls for state changes (or if it supports notifications for those), but would it be possible for your plugin to periodically (or after every command) poll for all device's state and (potentially) push these state changes to HomeKit?

(Also, I set up a docker image that allows one to run homebridge + hombridge-cec-accessory as a privileged container on a Raspberry Pi 3. I can send you a PR if you're interested.)

**Comment by jbree** [comment]
Thanks for pointing this out! I hadn't considered state changes other than those directly initiated by the user, and honestly I didn't know that homebridge supported this. I just looked at a couple other plugins and apparently it must be a thing, because how else would motion sensor accessories work? I'll see about getting this added in the next couple of weeks (busy, busy).

Not sure about putting the Docker image in here, seems like dockerhub is more the place for that. I'm open to being convinced otherwise if you think it belongs here. I'm happy to put a link to it in the readme, though. Docker definitely seems like a much simpler method than going through the install procedure I describe, though.

It would be great if you update the readme with instructions to install the docker image from dockerhub and PR that. Or write a snippet for me and I can paste it in.

Thanks again for the note, I'm glad the plugin is working for you!

**Comment by jbree** [comment]
Started looking at this today. Unfortunately, the CEC responses that I use to get status upon request from the devices appear to be different from the ones sent out when status changes occur, at least in some cases. Still investigating as spare time allows.

**Comment by drebes** [comment]
No worries, thanks for looking into this. I have no experience with Node.js but I can test with cec-utils on my hardware if you need any help.
