### ISSUE TITLE
Won't run as Systemd Service

### ISSUE THREAD

**Issue by stuarthenrywilson** [jbree/homebridge-cec-accessory#5]
Hi, I'm hoping you can help me out. When I run homebridge normally, your plugin works great (looking forward to being able to poll the accessories at some point) but when I run it as a systemd service, the accessories show up, but are listed as 'No response'. 

I've copied the config file to the correct directory (other plugins are working fine) so I'm not sure where I'm going wrong. Do you have any ideas?

Great work btw!

Thanks,

Stuart

**Comment by jbree** [comment]
Stuart,

Sorry for the delay, busy week.

I've been using an init.d script for my homebridge service rather than a systemd homebridge.service definition. Is this second way how you're doing it? My understanding is that running a systemd service with that mechanism requires a separate "homebridge" user added to the system. If this is the case, perhaps there is a permissions issue when the plugin tries to start `cec-client`.

A couple things to try: If this is how you're running it, try switching to the "homebridge" user and manually run homebridge. Any difference?

If nothing helpful comes out of that, I would check the systemd logs for your homebridge service, see if that gives any hints. Also, if you haven't tried restarting, sometimes that gets the `cec-client` portion of this going again.

**Comment by stuarthenrywilson** [comment]
It was indeed a permissions issue—which I figured out shortly after posting here—but I haven't had time to update this thread so do't worry about the delay, I understand busy.

Thanks for getting back to me, though.

Stuart

**Comment by jbree** [comment]
Great, I hope the plugin works out for you!

**Comment by rkok98** [comment]
Do you remember for which folder you changed the permission? I have the same problem as you, and I believe the same solution will solve it.

**Comment by jbree** [comment]
Reading back through this, I don't think it's a file permissions issue. My theory at the time was that it was an issue with the "homebridge" user having permissions to run the `cec-client` executable. If @stuarthenrywilson can weigh in, maybe he remembers more specifically.

**Comment by rkok98** [comment]
Yes, I can't figure out why though. 
I'm able to use e.g. "echo "on 0" | cec-client -s" on the same user.

**Comment by thehauntedmattress** [comment]
Hey I know this issue was closed but I believe I am having the same issue and was wondering what the steps were to rectify it.  I stopped my systemd homebridge service and ran homebridge just from the command line.  The homebridge-cec accessory worked when I ran homebridge from the command line, but not when systemd launched it.  Which folders or files do I need to modify?

**Comment by jbree** [comment]
@thehauntedmattress I've given my best advice above, which is that the user responsible for launching the `cec-client` process needs to have the correct permissions to launch the process. If that's not it, I really don't know. I'm not experienced with systemd.

**Comment by thehauntedmattress** [comment]
Where exactly is the process stored?

**Comment by jbree** [comment]
Usually stuff installed by your package manager will go into ‘/usr/local/bin’. you can find out for sure by running `which cec-client`. This tells you the path to the first instance of cec-client found on your $PATH.

**Comment by lechf** [comment]
I've been battling with this same problem tonight and I'm pleased to report I've found the solution.

Bare with me as I'm pretty green to all this..

Attempting to run cec-client as homebridge user was giving me errors about "vchiq"

A google led me here https://raspberrypi.stackexchange.com/questions/19436/how-can-i-permanently-fix-dev-vchiq-permission-errors

So I added the "homebridge" user to the "video" group 

sudo usermod -a -G video homebridge

I also did 

 sudo chown -R homebridge:homebridge /usr/bin/cec-client 

But not sure that was necessary.

**Comment by thehauntedmattress** [comment]
My solution to this was to install homebridge-ssh and just have it run the CEC commands that way.
